import {
  ROBOT_PROFILE_FORMAT,
  defineRobotProfile,
} from "../core/robot/profile.js";

const PROFILE_DEFINITIONS = [
  {
    format: ROBOT_PROFILE_FORMAT,
    id: "interbotix-wx250s",
    topology: "single",
    systemType: "single-arm",
    recordStatus: "reviewed",
    availabilityStatus: "commercial-kit-discontinued",
    model: "WIDOWX 250S",
    company: "INTERBOTIX / TROSSEN",
    country: "USA",
    countryCode: "US",
    region: "AMERICAN",
    openScope: "ROS 1 + ROS 2 MANIPULATOR PACKAGES",
    license: "BSD-3-CLAUSE",
    sourceUrl:
      "https://github.com/Interbotix/interbotix_ros_manipulators",
    productUrl:
      "https://docs.trossenrobotics.com/interbotix_xsarms_docs/",
    sourceReach: "650 MM PUBLISHED REACH / 250 G WORKING PAYLOAD",
    geometryTruth: "TEN PINNED OFFICIAL STL MESHES + SOURCE SIX-AXIS JOINT ORIGINS IN 3D / PUBLISHED REACH + NORMALIZED PLANAR 2D MISSION SOLVER",
    geometryStatus: "normalized",
    sourceCheckedAt: "2026-08-01",
    sources: [
      {
        sourceId: "software",
        kind: "source-repository",
        label: "Interbotix ROS manipulator packages",
        url: "https://github.com/Interbotix/interbotix_ros_manipulators",
      },
      {
        sourceId: "specifications",
        kind: "manufacturer-specification",
        label: "WidowX-250 6DOF specifications",
        url: "https://docs.trossenrobotics.com/interbotix_xsarms_docs/specifications/wx250s.html",
      },
      {
        sourceId: "product",
        kind: "manufacturer-product",
        label: "Interbotix X-Series documentation",
        url: "https://docs.trossenrobotics.com/interbotix_xsarms_docs/",
      },
    ],
    publishedClaims: [
      {
        claimId: "published-reach",
        label: "Published reach",
        value: "650 mm",
        status: "vendor-claimed",
        sourceIds: ["specifications"],
      },
      {
        claimId: "working-payload",
        label: "Published working payload",
        value: "250 g inside the recommended workspace",
        status: "vendor-claimed",
        sourceIds: ["specifications"],
      },
    ],
    linkLengths: [155, 150],
    jointsDegrees: [38, -54],
    target: { x: -100, y: 20 },
    elbow: "down",
    visual: {
      kind: "servo",
      primary: "#2f86ff",
      secondary: "#d8e7f5",
      shell: "#182330",
    },
    obstacles: [
      { id: "part-bin", type: "circle", x: -140, y: -50, radius: 30 },
    ],
    waypoints: [
      { id: "wx-a", label: "P1", x: 176, y: 150 },
      { id: "wx-b", label: "P2", x: -100, y: 20 },
    ],
  },
  {
    format: ROBOT_PROFILE_FORMAT,
    id: "niryo-ned2",
    topology: "single",
    systemType: "single-arm",
    recordStatus: "reviewed",
    model: "NED2",
    company: "NIRYO",
    country: "FRANCE",
    countryCode: "FR",
    region: "EUROPEAN",
    openScope: "FULL ROS STACK FOR NED",
    license: "GPL-3.0",
    sourceUrl: "https://github.com/NiryoRobotics/ned_ros",
    productUrl: "https://niryo.com/product/robotic-arm/",
    sourceReach: "490 MM",
    geometryTruth: "SOURCE REACH / NORMALIZED 2-LINK DRAWING",
    geometryStatus: "normalized",
    sourceCheckedAt: "2026-07-30",
    sources: [
      {
        sourceId: "software",
        kind: "source-repository",
        label: "Niryo Ned ROS stack",
        url: "https://github.com/NiryoRobotics/ned_ros",
      },
      {
        sourceId: "product",
        kind: "manufacturer-product",
        label: "Niryo robotic arm product page",
        url: "https://niryo.com/product/robotic-arm/",
      },
    ],
    publishedClaims: [
      {
        claimId: "published-reach",
        label: "Published reach",
        value: "490 mm",
        status: "vendor-claimed",
        sourceIds: ["product"],
      },
    ],
    linkLengths: [152, 132],
    jointsDegrees: [48, -62],
    target: { x: -100, y: 20 },
    elbow: "down",
    visual: {
      kind: "pod",
      primary: "#7f67ff",
      secondary: "#f4f2ed",
      shell: "#28243a",
    },
    obstacles: [
      { id: "training-puck", type: "circle", x: -140, y: -50, radius: 30 },
    ],
    waypoints: [
      { id: "ned-a", label: "P1", x: 154, y: 172 },
      { id: "ned-b", label: "P2", x: -100, y: 20 },
    ],
  },
  {
    format: ROBOT_PROFILE_FORMAT,
    id: "franka-research-3",
    topology: "single",
    systemType: "single-arm",
    recordStatus: "reviewed",
    model: "FRANKA RESEARCH 3",
    company: "FRANKA ROBOTICS",
    country: "GERMANY",
    countryCode: "DE",
    region: "EUROPEAN",
    openScope: "LOW-LEVEL CONTROL INTERFACE + ROS 2",
    license: "APACHE-2.0",
    sourceUrl: "https://github.com/frankarobotics/libfranka",
    productUrl: "https://franka.de/research",
    sourceReach: "855 MM",
    geometryTruth: "SOURCE REACH / NORMALIZED 2-LINK DRAWING",
    geometryStatus: "normalized",
    sourceCheckedAt: "2026-07-30",
    sources: [
      {
        sourceId: "software",
        kind: "source-repository",
        label: "Franka low-level control interface",
        url: "https://github.com/frankarobotics/libfranka",
      },
      {
        sourceId: "product",
        kind: "manufacturer-product",
        label: "Franka Research 3 product page",
        url: "https://franka.de/research",
      },
    ],
    publishedClaims: [
      {
        claimId: "published-reach",
        label: "Published reach",
        value: "855 mm",
        status: "vendor-claimed",
        sourceIds: ["product"],
      },
    ],
    linkLengths: [174, 136],
    jointsDegrees: [26, -48],
    target: { x: -180, y: -100 },
    elbow: "down",
    visual: {
      kind: "cobot",
      primary: "#ff9b56",
      secondary: "#f1eee7",
      shell: "#24211e",
    },
    obstacles: [
      { id: "camera", type: "circle", x: -180, y: -50, radius: 30 },
    ],
    waypoints: [
      { id: "fr3-a", label: "P1", x: 165, y: 176 },
      { id: "fr3-b", label: "P2", x: -180, y: -100 },
    ],
  },
  {
    format: ROBOT_PROFILE_FORMAT,
    id: "ur5e",
    topology: "single",
    systemType: "single-arm",
    recordStatus: "reviewed",
    model: "UR5E",
    company: "UNIVERSAL ROBOTS",
    country: "DENMARK",
    countryCode: "DK",
    region: "EUROPEAN",
    openScope: "ROS 2 DRIVER + DESCRIPTION PACKAGES",
    license: "BSD-3-CLAUSE",
    sourceUrl:
      "https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver",
    productUrl: "https://www.universal-robots.com/products/ur5-robot/",
    sourceReach: "850 MM",
    geometryTruth: "SOURCE REACH / NORMALIZED 2-LINK DRAWING",
    geometryStatus: "normalized",
    sourceCheckedAt: "2026-07-30",
    sources: [
      {
        sourceId: "software",
        kind: "source-repository",
        label: "Universal Robots ROS 2 driver",
        url: "https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver",
      },
      {
        sourceId: "product",
        kind: "manufacturer-product",
        label: "Universal Robots UR5e product page",
        url: "https://www.universal-robots.com/products/ur5-robot/",
      },
    ],
    publishedClaims: [
      {
        claimId: "published-reach",
        label: "Published reach",
        value: "850 mm",
        status: "vendor-claimed",
        sourceIds: ["product"],
      },
    ],
    linkLengths: [168, 142],
    jointsDegrees: [33, -56],
    target: { x: -100, y: 20 },
    elbow: "down",
    visual: {
      kind: "capsule",
      primary: "#16a9bd",
      secondary: "#d9eef0",
      shell: "#153034",
    },
    obstacles: [
      { id: "inspection", type: "circle", x: -140, y: -50, radius: 30 },
    ],
    waypoints: [
      { id: "ur-a", label: "P1", x: 162, y: 184 },
      { id: "ur-b", label: "P2", x: -100, y: 20 },
    ],
  },
  {
    format: ROBOT_PROFILE_FORMAT,
    id: "hello-stretch-4",
    topology: "single",
    systemType: "single-arm",
    recordStatus: "reviewed",
    model: "STRETCH 4",
    company: "HELLO ROBOT",
    country: "USA",
    countryCode: "US",
    region: "AMERICAN",
    openScope: "FULL-STACK SOFTWARE + ROS 2 SDK",
    license: "PACKAGE-SPECIFIC",
    sourceUrl: "https://github.com/hello-robot/stretch_ros2",
    productUrl: "https://hello-robot.com/stretch-4-product",
    sourceReach: "MOBILE MANIPULATOR",
    geometryTruth: "ARCHITECTURE ABSTRACTED AS A NORMALIZED 2-LINK ARM",
    geometryStatus: "normalized",
    sourceCheckedAt: "2026-07-30",
    sources: [
      {
        sourceId: "software",
        kind: "source-repository",
        label: "Hello Robot Stretch ROS 2 stack",
        url: "https://github.com/hello-robot/stretch_ros2",
      },
      {
        sourceId: "product",
        kind: "manufacturer-product",
        label: "Hello Robot Stretch 4 product page",
        url: "https://hello-robot.com/stretch-4-product",
      },
    ],
    publishedClaims: [
      {
        claimId: "mobile-manipulator",
        label: "Published system class",
        value: "Mobile manipulator",
        status: "vendor-claimed",
        sourceIds: ["product"],
      },
    ],
    linkLengths: [142, 156],
    jointsDegrees: [58, -72],
    target: { x: -100, y: 20 },
    elbow: "down",
    visual: {
      kind: "mobile",
      primary: "#ffe44c",
      secondary: "#e8e8df",
      shell: "#282819",
    },
    obstacles: [
      { id: "chair", type: "circle", x: -140, y: -50, radius: 30 },
    ],
    waypoints: [
      { id: "stretch-a", label: "P1", x: 136, y: 184 },
      { id: "stretch-b", label: "P2", x: -100, y: 20 },
    ],
  },
  {
    format: ROBOT_PROFILE_FORMAT,
    id: "aloha-stationary",
    topology: "dual",
    systemType: "published-dual",
    recordStatus: "reviewed",
    dualStatus: "PUBLISHED DUAL SYSTEM",
    model: "ALOHA STATIONARY",
    company: "TROSSEN / INTERBOTIX",
    country: "USA",
    countryCode: "US",
    region: "AMERICAN",
    openScope: "OPEN HARDWARE SYSTEM + TELEOPERATION CODE",
    license: "MIT + COMPONENT LICENSES",
    sourceUrl: "https://github.com/tonyzhaozh/aloha",
    productUrl:
      "https://docs.trossenrobotics.com/aloha_docs/1.0/specifications.html",
    sourceReach: "1225W × 1019D × 1066H MM CELL",
    geometryTruth: "SOURCE CELL ENVELOPE / NORMALIZED PER-ARM DRAWING",
    geometryStatus: "normalized",
    sourceCheckedAt: "2026-07-30",
    sources: [
      {
        sourceId: "software",
        kind: "source-repository",
        label: "ALOHA hardware and teleoperation repository",
        url: "https://github.com/tonyzhaozh/aloha",
      },
      {
        sourceId: "specifications",
        kind: "manufacturer-specification",
        label: "ALOHA Stationary specifications",
        url: "https://docs.trossenrobotics.com/aloha_docs/1.0/specifications.html",
      },
    ],
    publishedClaims: [
      {
        claimId: "cell-envelope",
        label: "Published cell envelope",
        value: "1225W × 1019D × 1066H mm",
        status: "vendor-claimed",
        sourceIds: ["specifications"],
      },
      {
        claimId: "follower-arms",
        label: "Published follower-arm count",
        value: "Two ViperX follower arms",
        status: "vendor-claimed",
        sourceIds: ["specifications"],
      },
    ],
    baseSeparation: 220,
    linkLengths: [126, 112],
    jointsDegrees: [48, -64],
    target: { x: -80, y: 20 },
    elbow: "down",
    visual: {
      kind: "servo",
      primary: "#3978ff",
      secondary: "#eef2f3",
      shell: "#1a2730",
    },
    obstacles: [
      { id: "aloha-part", type: "circle", x: -112, y: -42, radius: 26 },
    ],
    waypoints: [
      { id: "aloha-a", label: "P1", x: 128, y: 146 },
      { id: "aloha-b", label: "P2", x: -80, y: 20 },
    ],
  },
  {
    format: ROBOT_PROFILE_FORMAT,
    id: "fr3-duo",
    topology: "dual",
    systemType: "published-dual",
    recordStatus: "reviewed",
    dualStatus: "PUBLISHED DUAL SYSTEM",
    model: "FR3 DUO",
    company: "FRANKA ROBOTICS",
    country: "GERMANY",
    countryCode: "DE",
    region: "EUROPEAN",
    openScope: "FCI + LIBFRANKA + OPEN LABS WORKFLOWS",
    license: "APACHE-2.0 + COMPONENT LICENSES",
    sourceUrl: "https://github.com/frankarobotics/libfranka",
    productUrl: "https://franka.de/fr3-duo",
    sourceReach: "2 × 7 DOF / 3 KG PER ARM",
    geometryTruth: "SOURCE ARM COUNT + PAYLOAD / NORMALIZED DRAWING",
    geometryStatus: "normalized",
    sourceCheckedAt: "2026-07-30",
    sources: [
      {
        sourceId: "software",
        kind: "source-repository",
        label: "Franka low-level control interface",
        url: "https://github.com/frankarobotics/libfranka",
      },
      {
        sourceId: "product",
        kind: "manufacturer-product",
        label: "Franka FR3 Duo product page",
        url: "https://franka.de/fr3-duo",
      },
    ],
    publishedClaims: [
      {
        claimId: "arm-count",
        label: "Published arm count",
        value: "Two 7-DOF FR3 arms",
        status: "vendor-claimed",
        sourceIds: ["product"],
      },
      {
        claimId: "payload-per-arm",
        label: "Published payload per arm",
        value: "3 kg",
        status: "vendor-claimed",
        sourceIds: ["product"],
      },
    ],
    baseSeparation: 210,
    linkLengths: [132, 116],
    jointsDegrees: [36, -58],
    target: { x: -84, y: 24 },
    elbow: "down",
    visual: {
      kind: "cobot",
      primary: "#ff8c52",
      secondary: "#f2efe7",
      shell: "#28221e",
    },
    obstacles: [
      { id: "fr3-duo-part", type: "circle", x: -120, y: -44, radius: 26 },
    ],
    waypoints: [
      { id: "fr3d-a", label: "P1", x: 132, y: 150 },
      { id: "fr3d-b", label: "P2", x: -84, y: 24 },
    ],
  },
  {
    format: ROBOT_PROFILE_FORMAT,
    id: "toddlerbot-2",
    recordStatus: "reviewed",
    platformClass: "humanoid",
    mobilityType: "biped",
    simulationSupport: "catalog-only",
    simulationEngine: "locomotion-catalog",
    simulationNote:
      "SOURCE-BACKED CATALOG RECORD; NO BIPED DYNAMICS ENGINE IS CONNECTED",
    opennessStatus: "mixed-open-restricted",
    originBasis: "STANFORD UNIVERSITY PROJECT / UNITED STATES",
    supplyChainStatus: "not-assessed",
    availabilityStatus: "self-build",
    model: "TODDLERBOT 2.0",
    company: "STANFORD ROBOTICS",
    country: "USA",
    countryCode: "US",
    region: "AMERICAN",
    openScope:
      "MIT SOFTWARE / CC BY-NC-SA 4.0 NON-COMMERCIAL HARDWARE",
    license: "MIT SOFTWARE + CC BY-NC-SA 4.0 HARDWARE",
    sourceUrl: "https://github.com/hshi74/toddlerbot",
    productUrl: "https://hshi74.github.io/toddlerbot/",
    sourceReach: "30 ACTIVE DOF / 0.56 M / 3.4 KG",
    geometryTruth: "SOURCE 30-DOF URDF TOPOLOGY + PUBLISHED HEIGHT / APPROXIMATE PLAN ENVELOPE / NO GAIT DYNAMICS",
    geometryStatus: "inferred",
    sourceCheckedAt: "2026-08-01",
    sources: [
      {
        sourceId: "software",
        kind: "source-repository",
        label: "ToddlerBot software and hardware repository",
        url: "https://github.com/hshi74/toddlerbot",
      },
      {
        sourceId: "documentation",
        kind: "project-documentation",
        label: "ToddlerBot 2.0 project documentation",
        url: "https://hshi74.github.io/toddlerbot/",
      },
      {
        sourceId: "paper",
        kind: "research-paper",
        label: "ToddlerBot open-source humanoid paper",
        url: "https://arxiv.org/abs/2409.16658",
      },
    ],
    publishedClaims: [
      {
        claimId: "active-dof",
        label: "Active degrees of freedom",
        value: "30",
        status: "observed",
        sourceIds: ["documentation", "paper"],
      },
      {
        claimId: "size-and-mass",
        label: "Published size and mass",
        value: "0.56 m / 3.4 kg",
        status: "observed",
        sourceIds: ["paper"],
      },
    ],
    visual: {
      kind: "humanoid",
      primary: "#ff6b36",
      secondary: "#f0efe9",
      shell: "#242321",
    },
  },
  {
    format: ROBOT_PROFILE_FORMAT,
    id: "poppy-humanoid",
    recordStatus: "reviewed",
    platformClass: "humanoid",
    mobilityType: "biped",
    simulationSupport: "catalog-only",
    simulationEngine: "locomotion-catalog",
    simulationNote:
      "SOURCE-BACKED CATALOG RECORD; NO BIPED DYNAMICS ENGINE IS CONNECTED",
    opennessStatus: "open-platform",
    originBasis: "POPPY PROJECT ORIGINATED AT INRIA BORDEAUX / FRANCE",
    supplyChainStatus: "not-assessed",
    availabilityStatus: "self-build",
    model: "POPPY HUMANOID",
    company: "POPPY PROJECT / INRIA",
    country: "FRANCE",
    countryCode: "FR",
    region: "EUROPEAN",
    openScope: "OPEN CAD + CC BY-SA HARDWARE / GPL-3.0 SOFTWARE",
    license: "CC BY-SA HARDWARE + GPL-3.0 SOFTWARE",
    sourceUrl: "https://github.com/poppy-project/poppy-humanoid",
    productUrl: "https://www.poppy-project.org/en/robots/poppy-humanoid/",
    sourceReach: "83 CM / 3.5 KG / 25 ACTUATORS",
    geometryTruth: "CATALOG SPECS ONLY / SILHOUETTE IS NOT DIMENSIONED GEOMETRY",
    geometryStatus: "unverified",
    sourceCheckedAt: "2026-07-30",
    sources: [
      {
        sourceId: "hardware",
        kind: "source-repository",
        label: "Poppy Humanoid hardware repository",
        url: "https://github.com/poppy-project/poppy-humanoid",
      },
      {
        sourceId: "project",
        kind: "project-documentation",
        label: "Poppy Humanoid project page",
        url: "https://www.poppy-project.org/en/robots/poppy-humanoid/",
      },
    ],
    publishedClaims: [
      {
        claimId: "size-mass-actuators",
        label: "Published size, mass, and actuator count",
        value: "83 cm / 3.5 kg / 25 actuators",
        status: "observed",
        sourceIds: ["project", "hardware"],
      },
    ],
    visual: {
      kind: "humanoid",
      primary: "#00a878",
      secondary: "#eef4ef",
      shell: "#18332b",
    },
  },
  {
    format: ROBOT_PROFILE_FORMAT,
    id: "pupper-v3",
    recordStatus: "reviewed",
    platformClass: "quadruped",
    mobilityType: "quadruped",
    simulationSupport: "catalog-only",
    simulationEngine: "locomotion-catalog",
    simulationNote:
      "CATALOG RECORD; UPSTREAM MUJOCO WORK EXISTS BUT IS NOT EMBEDDED HERE",
    opennessStatus: "open-platform",
    originBasis: "STANFORD-ROOTED HANDS-ON ROBOTICS PROJECT / UNITED STATES",
    supplyChainStatus: "mixed",
    availabilityStatus: "self-build",
    model: "PUPPER V3",
    company: "HANDS-ON ROBOTICS",
    country: "USA",
    countryCode: "US",
    region: "AMERICAN",
    openScope: "PUBLIC CAD + BUILD FILES / GPL-3.0 SOFTWARE MONOREPO",
    license: "GPL-3.0 SOFTWARE; HARDWARE TERMS NOT SEPARATELY STATED",
    sourceUrl: "https://github.com/Nate711/pupperv3-monorepo",
    productUrl: "https://pupper-v3-documentation.readthedocs.io/en/latest/",
    sourceReach: "12 DOF / 3 KG / 25 × 22 × 20 CM CROUCHED",
    geometryTruth: "SOURCE 12-DOF URDF TOPOLOGY + PUBLISHED CROUCHED ENVELOPE / NO GAIT OR CONTACT DYNAMICS",
    geometryStatus: "source-dimensioned",
    sourceCheckedAt: "2026-08-01",
    sources: [
      {
        sourceId: "software",
        kind: "source-repository",
        label: "Pupper v3 public monorepo",
        url: "https://github.com/Nate711/pupperv3-monorepo",
      },
      {
        sourceId: "documentation",
        kind: "project-documentation",
        label: "Pupper v3 build and learning documentation",
        url: "https://pupper-v3-documentation.readthedocs.io/en/latest/",
      },
      {
        sourceId: "specifications",
        kind: "project-documentation",
        label: "Pupper v3 technical specifications",
        url: "https://pupper-v3-documentation.readthedocs.io/en/latest/learn_more/tech_specs.html",
      },
    ],
    publishedClaims: [
      {
        claimId: "degrees-of-freedom",
        label: "Published degrees of freedom",
        value: "12 / three per leg",
        status: "observed",
        sourceIds: ["specifications"],
      },
      {
        claimId: "mass-and-size",
        label: "Published mass and crouched size",
        value: "3 kg / 25 × 22 × 20 cm",
        status: "observed",
        sourceIds: ["specifications"],
      },
    ],
    visual: {
      kind: "quadruped",
      primary: "#f1bd17",
      secondary: "#f2f0e8",
      shell: "#312d18",
    },
  },
  {
    format: ROBOT_PROFILE_FORMAT,
    id: "solo-12",
    recordStatus: "reviewed",
    platformClass: "quadruped",
    mobilityType: "quadruped",
    simulationSupport: "catalog-only",
    simulationEngine: "locomotion-catalog",
    simulationNote:
      "SOURCE-BACKED CATALOG RECORD; NO QUADRUPED DYNAMICS ENGINE IS CONNECTED",
    opennessStatus: "open-platform",
    originBasis:
      "MAX PLANCK / LAAS-CNRS EUROPEAN-LED OPEN DYNAMIC ROBOT INITIATIVE",
    supplyChainStatus: "not-assessed",
    availabilityStatus: "commercial-kit-discontinued",
    model: "SOLO 12",
    company: "OPEN DYNAMIC ROBOT INITIATIVE",
    country: "GERMANY",
    countryCode: "DE",
    region: "EUROPEAN",
    openScope: "OPEN MECHANICS + ELECTRONICS + CONTROL SOFTWARE",
    license: "BSD-3-CLAUSE",
    sourceUrl:
      "https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware",
    productUrl: "https://inria-paris-robotics-lab.github.io/Robots/Solo.html",
    sourceReach: "12 DOF / LIGHTWEIGHT TORQUE-CONTROLLED QUADRUPED",
    geometryTruth: "CATALOG SPECS ONLY / SILHOUETTE IS NOT DIMENSIONED GEOMETRY",
    geometryStatus: "unverified",
    sourceCheckedAt: "2026-07-30",
    sources: [
      {
        sourceId: "hardware",
        kind: "source-repository",
        label: "Open Robot Actuator Hardware / Solo 12",
        url: "https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware",
      },
      {
        sourceId: "project",
        kind: "project-documentation",
        label: "Inria Paris Robotics Lab Solo page",
        url: "https://inria-paris-robotics-lab.github.io/Robots/Solo.html",
      },
    ],
    publishedClaims: [
      {
        claimId: "degrees-of-freedom",
        label: "Published degrees of freedom",
        value: "12",
        status: "observed",
        sourceIds: ["hardware", "project"],
      },
      {
        claimId: "commercial-availability",
        label: "Commercial kit status",
        value: "Discontinued; open self-build records remain",
        status: "observed",
        sourceIds: ["project"],
      },
    ],
    visual: {
      kind: "quadruped",
      primary: "#e64b3c",
      secondary: "#efefec",
      shell: "#30201f",
    },
  },
  {
    format: ROBOT_PROFILE_FORMAT,
    id: "crazyflie-2-1-plus",
    recordStatus: "reviewed",
    platformClass: "drone",
    mobilityType: "multirotor",
    simulationSupport: "catalog-only",
    simulationEngine: "flight-catalog",
    simulationNote:
      "SOURCE-BACKED CATALOG RECORD; NO FLIGHT DYNAMICS ENGINE IS CONNECTED",
    opennessStatus: "mixed-open-restricted",
    originBasis: "BITCRAZE AB / SWEDEN",
    supplyChainStatus: "not-assessed",
    availabilityStatus: "commercial-product",
    model: "CRAZYFLIE 2.1+",
    company: "BITCRAZE",
    country: "SWEDEN",
    countryCode: "SE",
    region: "EUROPEAN",
    openScope: "OPEN-SOURCE FIRMWARE / SEMI-OPEN HARDWARE SCHEMATICS",
    license: "LGPL-3.0 FIRMWARE; HARDWARE TERMS VARY BY REVISION",
    sourceUrl: "https://github.com/bitcraze/crazyflie-firmware",
    productUrl: "https://www.bitcraze.io/products/crazyflie-2-1-plus/",
    sourceReach: "29 G / 92 × 92 × 29 MM / 7 MIN FLIGHT",
    geometryTruth: "PUBLISHED 92 × 92 × 29 MM AIRFRAME / PARAMETRIC SILHOUETTE / NO FLIGHT DYNAMICS",
    geometryStatus: "source-dimensioned",
    sourceCheckedAt: "2026-08-01",
    sources: [
      {
        sourceId: "firmware",
        kind: "source-repository",
        label: "Crazyflie firmware repository",
        url: "https://github.com/bitcraze/crazyflie-firmware",
      },
      {
        sourceId: "product",
        kind: "manufacturer-product",
        label: "Crazyflie 2.1+ product page",
        url: "https://www.bitcraze.io/products/crazyflie-2-1-plus/",
      },
      {
        sourceId: "openness",
        kind: "manufacturer-about",
        label: "Bitcraze open-source philosophy and hardware scope",
        url: "https://www.bitcraze.io/open-source-philosophy/",
      },
    ],
    publishedClaims: [
      {
        claimId: "mass-and-size",
        label: "Published mass and dimensions",
        value: "29 g / 92 × 92 × 29 mm",
        status: "vendor-claimed",
        sourceIds: ["product"],
      },
      {
        claimId: "flight-time",
        label: "Published flight time",
        value: "7 minutes",
        status: "vendor-claimed",
        sourceIds: ["product"],
      },
    ],
    visual: {
      kind: "drone",
      primary: "#e3342f",
      secondary: "#f2f2ef",
      shell: "#291b1a",
    },
  },
  {
    format: ROBOT_PROFILE_FORMAT,
    id: "agilicious",
    recordStatus: "reviewed",
    platformClass: "drone",
    mobilityType: "multirotor",
    simulationSupport: "catalog-only",
    simulationEngine: "flight-catalog",
    simulationNote:
      "RESEARCH CATALOG RECORD; NO FLIGHT DYNAMICS ENGINE IS CONNECTED",
    opennessStatus: "source-available-restricted",
    originBasis: "UNIVERSITY OF ZURICH ROBOTICS AND PERCEPTION GROUP / SWITZERLAND",
    supplyChainStatus: "not-assessed",
    availabilityStatus: "research-release",
    model: "AGILICIOUS",
    company: "UZH ROBOTICS & PERCEPTION GROUP",
    country: "SWITZERLAND",
    countryCode: "CH",
    region: "EUROPEAN",
    openScope:
      "SOFTWARE + HARDWARE SOURCE / ACADEMIC NON-COMMERCIAL USE ONLY",
    license: "UZH ACADEMIC NON-COMMERCIAL LICENSE",
    sourceUrl: "https://github.com/uzh-rpg/agilicious",
    productUrl: "https://rpg.ifi.uzh.ch/agilicious.html",
    sourceReach: "UP TO 5 G / 70 KM/H RESEARCH FLIGHT DEMONSTRATIONS",
    geometryTruth: "CATALOG SPECS ONLY / SILHOUETTE IS NOT DIMENSIONED GEOMETRY",
    geometryStatus: "unverified",
    sourceCheckedAt: "2026-07-30",
    sources: [
      {
        sourceId: "software",
        kind: "source-repository",
        label: "Agilicious software and hardware repository",
        url: "https://github.com/uzh-rpg/agilicious",
      },
      {
        sourceId: "project",
        kind: "project-documentation",
        label: "UZH Agilicious research project page",
        url: "https://rpg.ifi.uzh.ch/agilicious.html",
      },
      {
        sourceId: "license",
        kind: "project-documentation",
        label: "Agilicious academic non-commercial license",
        url: "https://github.com/uzh-rpg/agilicious/blob/main/LICENSE",
      },
    ],
    publishedClaims: [
      {
        claimId: "flight-envelope",
        label: "Published research flight demonstrations",
        value: "Up to 5 g and 70 km/h",
        status: "observed",
        sourceIds: ["software", "project"],
      },
      {
        claimId: "license-boundary",
        label: "Use restriction",
        value: "Academic and non-commercial only",
        status: "observed",
        sourceIds: ["license"],
      },
    ],
    visual: {
      kind: "drone",
      primary: "#00a7a0",
      secondary: "#e9f2f0",
      shell: "#15302f",
    },
  },
];

export const ROBOT_PROFILES = PROFILE_DEFINITIONS.map((profile) =>
  defineRobotProfile({
    platformClass: "arm",
    mobilityType:
      profile.visual.kind === "mobile" ? "mobile-manipulator" : "fixed-base",
    simulationSupport: "interactive",
    simulationEngine: "planar-arm-v1",
    simulationNote:
      "INTERACTIVE PLANAR TEACHING MODEL; NOT A VENDOR DIGITAL TWIN",
    opennessStatus: "open-component",
    originBasis: `${profile.company} PROJECT OR COMPANY RECORD / ${profile.country}`,
    supplyChainStatus: "not-assessed",
    availabilityStatus: "commercial-product",
    ...profile,
  })
);

export function getRobotProfile(id) {
  return ROBOT_PROFILES.find((profile) => profile.id === id) || ROBOT_PROFILES[0];
}

export function getRobotProfilesByTopology(topology) {
  return ROBOT_PROFILES.filter((profile) => profile.topology === topology);
}

export function getRobotProfilesByPlatformClass(platformClass) {
  return ROBOT_PROFILES.filter(
    (profile) => profile.platformClass === platformClass
  );
}

export function getInteractiveRobotProfiles() {
  return ROBOT_PROFILES.filter(
    (profile) => profile.simulationSupport === "interactive"
  );
}

export function canLaunchPlanarWorkbench(profile) {
  return Boolean(
    profile &&
      profile.platformClass === "arm" &&
      profile.simulationSupport === "interactive" &&
      profile.simulationEngine === "planar-arm-v1"
  );
}
