export const ROBOT_PROFILES = [
  {
    id: "interbotix-wx250s",
    model: "WIDOWX 250S",
    company: "INTERBOTIX / TROSSEN",
    country: "USA",
    countryCode: "US",
    region: "AMERICAN",
    openScope: "ROS 1 + ROS 2 MANIPULATOR PACKAGES",
    license: "BSD-3-CLAUSE",
    sourceUrl:
      "https://github.com/Interbotix/interbotix_ros_manipulators",
    productUrl:
      "https://docs.trossenrobotics.com/interbotix_xsarms_docs/",
    sourceReach: "679 MM TO FINGERTIP",
    linkLengths: [155, 150],
    jointsDegrees: [38, -54],
    target: { x: -100, y: 20 },
    elbow: "down",
    visual: {
      kind: "servo",
      primary: "#2f86ff",
      secondary: "#d8e7f5",
      shell: "#182330",
    },
    obstacles: [
      { id: "part-bin", type: "circle", x: -140, y: -50, radius: 30 },
    ],
    waypoints: [
      { id: "wx-a", label: "P1", x: 176, y: 150 },
      { id: "wx-b", label: "P2", x: -100, y: 20 },
    ],
  },
  {
    id: "niryo-ned2",
    model: "NED2",
    company: "NIRYO",
    country: "FRANCE",
    countryCode: "FR",
    region: "EUROPEAN",
    openScope: "FULL ROS STACK FOR NED",
    license: "GPL-3.0",
    sourceUrl: "https://github.com/NiryoRobotics/ned_ros",
    productUrl: "https://niryo.com/product/robotic-arm/",
    sourceReach: "490 MM",
    linkLengths: [152, 132],
    jointsDegrees: [48, -62],
    target: { x: -100, y: 20 },
    elbow: "down",
    visual: {
      kind: "pod",
      primary: "#7f67ff",
      secondary: "#f4f2ed",
      shell: "#28243a",
    },
    obstacles: [
      { id: "training-puck", type: "circle", x: -140, y: -50, radius: 30 },
    ],
    waypoints: [
      { id: "ned-a", label: "P1", x: 154, y: 172 },
      { id: "ned-b", label: "P2", x: -100, y: 20 },
    ],
  },
  {
    id: "franka-research-3",
    model: "FRANKA RESEARCH 3",
    company: "FRANKA ROBOTICS",
    country: "GERMANY",
    countryCode: "DE",
    region: "EUROPEAN",
    openScope: "LOW-LEVEL CONTROL INTERFACE + ROS 2",
    license: "APACHE-2.0",
    sourceUrl: "https://github.com/frankarobotics/libfranka",
    productUrl: "https://franka.de/research",
    sourceReach: "855 MM",
    linkLengths: [174, 136],
    jointsDegrees: [26, -48],
    target: { x: -180, y: -100 },
    elbow: "down",
    visual: {
      kind: "cobot",
      primary: "#ff9b56",
      secondary: "#f1eee7",
      shell: "#24211e",
    },
    obstacles: [
      { id: "camera", type: "circle", x: -180, y: -50, radius: 30 },
    ],
    waypoints: [
      { id: "fr3-a", label: "P1", x: 165, y: 176 },
      { id: "fr3-b", label: "P2", x: -180, y: -100 },
    ],
  },
  {
    id: "ur5e",
    model: "UR5E",
    company: "UNIVERSAL ROBOTS",
    country: "DENMARK",
    countryCode: "DK",
    region: "EUROPEAN",
    openScope: "ROS 2 DRIVER + DESCRIPTION PACKAGES",
    license: "BSD-3-CLAUSE",
    sourceUrl:
      "https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver",
    productUrl: "https://www.universal-robots.com/products/ur5-robot/",
    sourceReach: "850 MM",
    linkLengths: [168, 142],
    jointsDegrees: [33, -56],
    target: { x: -100, y: 20 },
    elbow: "down",
    visual: {
      kind: "capsule",
      primary: "#16a9bd",
      secondary: "#d9eef0",
      shell: "#153034",
    },
    obstacles: [
      { id: "inspection", type: "circle", x: -140, y: -50, radius: 30 },
    ],
    waypoints: [
      { id: "ur-a", label: "P1", x: 162, y: 184 },
      { id: "ur-b", label: "P2", x: -100, y: 20 },
    ],
  },
  {
    id: "hello-stretch-4",
    model: "STRETCH 4",
    company: "HELLO ROBOT",
    country: "USA",
    countryCode: "US",
    region: "AMERICAN",
    openScope: "FULL-STACK SOFTWARE + ROS 2 SDK",
    license: "PACKAGE-SPECIFIC",
    sourceUrl: "https://github.com/hello-robot/stretch_ros2",
    productUrl: "https://hello-robot.com/stretch-4-product",
    sourceReach: "MOBILE MANIPULATOR",
    linkLengths: [142, 156],
    jointsDegrees: [58, -72],
    target: { x: -100, y: 20 },
    elbow: "down",
    visual: {
      kind: "mobile",
      primary: "#ffe44c",
      secondary: "#e8e8df",
      shell: "#282819",
    },
    obstacles: [
      { id: "chair", type: "circle", x: -140, y: -50, radius: 30 },
    ],
    waypoints: [
      { id: "stretch-a", label: "P1", x: 136, y: 184 },
      { id: "stretch-b", label: "P2", x: -100, y: 20 },
    ],
  },
];

export function getRobotProfile(id) {
  return ROBOT_PROFILES.find((profile) => profile.id === id) || ROBOT_PROFILES[0];
}
